networks:
  airflow_net:
    driver: bridge

# Centralisation des configurations Airflow pour éviter la duplication
x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: docker/Dockerfile
  environment:
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__WEBSERVER__SECRET_KEY=cle_secrete
    # Connexions automatiques (persistance par variables d'environnement)
    - AIRFLOW_CONN_FS_DEFAULT=file:///opt/airflow/data
    - AIRFLOW_CONN_MONGO_DEFAULT=mongodb://admin:password@ecommerce_mongodb:27017/
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
  networks:
    - airflow_net

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - airflow_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8090:8080"
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin || true && airflow webserver"

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    depends_on:
      postgres:
        condition: service_healthy
    command: scheduler

  ecommerce_mongodb:
    image: mongo:6.0
    container_name: ecommerce_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - airflow_net
    ports:
      - "27018:27017" 
    volumes:
      - ./docker/mongodb_data:/data/db

  jenkins:
    build:
      context: .
      dockerfile: docker/Dockerfile.jenkins
    container_name: jenkins_server
    ports:
      - "8082:8080"
      - "50001:50000"
    volumes:
      - ./docker/jenkins_home:/var/jenkins_home
      # Montage du socket Docker pour permettre au pipeline Jenkins de lancer des conteneurs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/opt/airflow/data
    networks:
      - airflow_net