FROM jenkins/jenkins:lts

USER root
# Installation de Docker pour que Jenkins puisse exécuter des commandes docker
RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*

# Ajout de l'utilisateur jenkins au groupe docker pour avoir les droits
RUN usermod -aG docker jenkins

# Installation automatique des plugins nécessaires
RUN jenkins-plugin-cli --plugins workflow-aggregator git docker-workflow

USER jenkins
